### PR TITLE
new item

### PR DESCRIPTION
**Pull request by DESTHUbb**
old item
18 ax.set_zlabel('')
new item:
18 ax.set_zlabel('Volume')

### CODE REVIEW

**Comment by CHADHUB007** [comment]
Thanks for adding the "Volume" tag

**Comment by DESTHUbb** [comment]
the result would be the following: import yfinance as yf
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

stock_data = yf.download("AAPL", start="2010-01-01", end="2023-04-01")

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x = np.arange(len(stock_data))
y = stock_data['Close']
z = np.zeros(len(stock_data))

ax.plot(x, y, z)
ax.set_xlabel('Days')
ax.set_ylabel('closing price')
ax.set_zlabel('Volume')

plt.show()

image

**Comment by CHADHUB007** [comment]
thanks for the change, I knew I was missing something👏

**Comment by DESTHUbb** [comment]
I'll be here if you need me on any more problems to solve

**Pull request merged**
